# Generated by Django 4.2.7 on 2023-11-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='Grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='School',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='Grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='School',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registeredschool',
            name='school',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
