# Generated by Django 4.2.7 on 2023-11-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyms', '0002_alter_answer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='private',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
