# Generated by Django 4.2.7 on 2023-11-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyms', '0002_answer_grade_answer_school_answer_is_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
