# Generated by Django 4.2.7 on 2023-11-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyms', '0003_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=100),
        ),
    ]
