# Generated by Django 4.2.7 on 2023-11-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyms', '0006_question_voter_alter_answer_user_alter_answer_voter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
